default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: shifts_agenda_development
  pool: 50

test:
  <<: *default
  database: "shifts_agenda_test"

production:
  <<: *default
  database: shifts_agenda_production
  username: shifts_agenda
  password: <%= ENV['SHIFTS_AGENDA_DATABASE_PASSWORD'] %>
